# PhiUSIIL-A2 → PhreshPhish-A2 zero-shot transfer

Train LightGBM and XGBoost on PhiUSIIL only; freeze model and threshold (0.5); evaluate cleaned PhreshPhish temporal test without retraining. Shared Experiment 5 A2 extractor, exact 18-feature order. Positive class phishing (`y_phish=1`). Five seeds: 13, 42, 2024, 777, 31415. Primary seed 42. PhiUSIIL in-domain A2 test is a separate, non-paired reference. Exploratory: the target set was inspected in prior work.

In [1]:
from pathlib import Path
import sys, json, hashlib, importlib.metadata as md, platform, time
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, precision_score, recall_score, roc_auc_score, average_precision_score, matthews_corrcoef, confusion_matrix
ROOT = Path.cwd().resolve()
while not (ROOT / "Experiment/5 - PhiUSIIL Focused Ablation/src").is_dir():
    if ROOT.parent == ROOT: raise RuntimeError("Run from workspace root or this experiment directory")
    ROOT = ROOT.parent
HERE = ROOT / "Experiment/6 - Cross-Corpus Transfer"
EXP5 = ROOT / "Experiment/5 - PhiUSIIL Focused Ablation"
sys.path.insert(0, str(EXP5))
from src.features import FEATURE_ORDER, url_features, domain_for
from src.data import MODEL_PARAMS, SEEDS, load_phiusiil, load_split, PHRESH_DIR
from src.run_experiment import build_model
assert len(FEATURE_ORDER) == 18 and len(set(FEATURE_ORDER)) == 18
print("workspace", ROOT, "ordered A2 features", FEATURE_ORDER, "seeds", SEEDS)

workspace E:\Kuliah\Tugas Akhir ordered A2 features ['URLLength', 'DomainLength', 'TLDLength', 'NoOfSubDomain', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL', 'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 'SpacialCharRatioInURL', 'IsHTTPS', 'HasObfuscation', 'IsDomainIP'] seeds [13, 42, 2024, 777, 31415]

## Frozen protocol and label verification
PhiUSIIL `train` IDs from frozen random split seed 42 are the only training rows; `val` and `test` do not enter fitting. PhiUSIIL source label is benign=1/phish=0, transformed as `y_phish=1-label`. PhreshPhish source strings map benign→0, phish→1 and are asserted equal to the audited target labels. Target is Experiment 4's cleaned temporal `split_test.csv.gz`; join URLs by immutable `row_id` reconstructed from original test shards and source row position. A2 features are extracted identically from raw URLs, float64, with no learned preprocessing. Model parameters from Experiment 5; four threads; fixed threshold 0.5.

In [2]:
def sha256(path):
    h=hashlib.sha256()
    with open(path,"rb") as f:
        for block in iter(lambda:f.read(1<<20),b""): h.update(block)
    return h.hexdigest()

def extract(urls):
    return pd.DataFrame([url_features(str(u)) for u in urls], columns=FEATURE_ORDER, dtype="float64")

phi_path=ROOT/"Experiment/1 - PhiUSIIL Cleaning + Leakage-Audit Notebook/phiusill_clean/phiusiil_clean.parquet"
split_path=ROOT/"Experiment/1 - PhiUSIIL Cleaning + Leakage-Audit Notebook/phiusill_clean/split_random.csv"
phresh_root=ROOT/"Experiment/4 - PhreshPhish Temporal Audit"
target_path=phresh_root/"outputs/20261022T170935017991Z/split_test.csv.gz"
assert target_path.exists()
# Raw target URLs are used only to reconstruct the already-cleaned target cohort.
parts=[]
for shard in sorted(PHRESH_DIR.glob("test-*.parquet")):
    part=pd.read_parquet(shard,columns=["url","label"])
    part["source_file"]=shard.name
    part["source_row"]=np.arange(len(part))
    parts.append(part)
raw_test=pd.concat(parts,ignore_index=True)
raw_test["row_id"]="test:"+raw_test.source_file+":"+raw_test.source_row.astype(str)
target=pd.read_csv(target_path).merge(raw_test[["row_id","url","label"]],on="row_id",how="left",validate="one_to_one")
assert target.url.notna().all() and target.label.notna().all()
target["label"]=target.label.map({"benign":0,"phish":1}).astype(int)
assert np.array_equal(target.label.to_numpy(),target.y_phish.to_numpy())

phi=load_phiusiil().set_index("url_id")
train_ids,test_ids=load_split("random",42)
Xtr=extract(phi.loc[train_ids.url_id,"URL"])
ytr=phi.loc[train_ids.url_id,"y_phish"].astype(int).to_numpy()
Xref=extract(phi.loc[test_ids.url_id,"URL"])
yref=phi.loc[test_ids.url_id,"y_phish"].astype(int).to_numpy()
Xt=extract(target.url)
yt=target.label.to_numpy()
assert Xtr.columns.tolist()==Xref.columns.tolist()==Xt.columns.tolist()==FEATURE_ORDER
assert set(np.unique(ytr))==set(np.unique(yref))==set(np.unique(yt))=={0,1}
print("train",Xtr.shape,"PhiUSIIL reference",Xref.shape,"PhreshPhish target",Xt.shape,"phishing-positive labels verified")

train (141222, 18) PhiUSIIL reference (47074, 18) PhreshPhish target (168035, 18) phishing-positive labels verified

## Source-only fits and saved predictions
Ten fits total: two model families × five fixed seeds. Each model sees PhiUSIIL training rows only. Threshold and all fitted preprocessing remain fixed for both cohorts.

In [3]:
OUT=HERE/"outputs"
OUT.mkdir(exist_ok=True)
THRESHOLD=0.5
PRIMARY_SEED=42
BOOT_REPS=1000
BOOT_SEED=42

def score(y,p):
    pred=(np.asarray(p)>=THRESHOLD).astype(int)
    tn,fp,fn,tp=confusion_matrix(y,pred,labels=[0,1]).ravel()
    return {"n":len(y),"tn":int(tn),"fp":int(fp),"fn":int(fn),"tp":int(tp),
      "f1_phish":f1_score(y,pred,zero_division=0),"precision_phish":precision_score(y,pred,zero_division=0),
      "recall_phish":recall_score(y,pred,zero_division=0),"fpr_benign":fp/(fp+tn) if tn+fp else np.nan,
      "miss_phish":fn/(fn+tp) if fn+tp else np.nan,"roc_auc":roc_auc_score(y,p),
      "average_precision":average_precision_score(y,p),"mcc":matthews_corrcoef(y,pred)}

metrics=[]
prediction_files=[]
for model_name in ("lightgbm","xgboost"):
    for seed in SEEDS:
        model=build_model(model_name,seed,4)
        started=time.perf_counter(); model.fit(Xtr,ytr); fit_seconds=time.perf_counter()-started
        assert np.array_equal(np.asarray(model.classes_),[0,1])
        for cohort,X,y,row_ids,domains in [
            ("phreshphish_temporal_test",Xt,yt,target.row_id.astype(str).to_numpy(),target.domain.astype(str).to_numpy()),
            ("phiusiil_random_test_reference",Xref,yref,test_ids.url_id.to_numpy(),[domain_for(u) for u in phi.loc[test_ids.url_id,"URL"]])]:
            p=model.predict_proba(X)[:,1]
            frame=pd.DataFrame({"cohort":cohort,"model":model_name,"seed":seed,"row_id":row_ids,"domain":domains,"y_phish":y,"p_phish":p,"pred":(p>=THRESHOLD).astype(int)})
            path=OUT/f"predictions_{cohort}_{model_name}_seed{seed}.csv.gz"
            frame.to_csv(path,index=False,compression="gzip"); prediction_files.append(path)
            metrics.append({"cohort":cohort,"model":model_name,"seed":seed,"fit_seconds":fit_seconds,"threshold":THRESHOLD,**score(y,p)})
            print(cohort,model_name,seed,"fit_seconds",round(fit_seconds,2))
metrics_df=pd.DataFrame(metrics)
metrics_path=OUT/"metrics.csv"; metrics_df.to_csv(metrics_path,index=False)
display(metrics_df)

phreshphish_temporal_test lightgbm 13 fit_seconds 2.22

phiusiil_random_test_reference lightgbm 13 fit_seconds 2.22

phreshphish_temporal_test lightgbm 42 fit_seconds 2.03

phiusiil_random_test_reference lightgbm 42 fit_seconds 2.03

phreshphish_temporal_test lightgbm 2024 fit_seconds 2.2

phiusiil_random_test_reference lightgbm 2024 fit_seconds 2.2

phreshphish_temporal_test lightgbm 777 fit_seconds 2.1

phiusiil_random_test_reference lightgbm 777 fit_seconds 2.1

phreshphish_temporal_test lightgbm 31415 fit_seconds 2.05

phiusiil_random_test_reference lightgbm 31415 fit_seconds 2.05

phreshphish_temporal_test xgboost 13 fit_seconds 2.35

phiusiil_random_test_reference xgboost 13 fit_seconds 2.35

phreshphish_temporal_test xgboost 42 fit_seconds 1.82

phiusiil_random_test_reference xgboost 42 fit_seconds 1.82

phreshphish_temporal_test xgboost 2024 fit_seconds 1.9

phiusiil_random_test_reference xgboost 2024 fit_seconds 1.9

phreshphish_temporal_test xgboost 777 fit_seconds 1.79

phiusiil_random_test_reference xgboost 777 fit_seconds 1.79

phreshphish_temporal_test xgboost 31415 fit_seconds 2.19

phiusiil_random_test_reference xgboost 31415 fit_seconds 2.19

,cohort,model,seed,fit_seconds,threshold,n,tn,fp,fn,tp,f1_phish,precision_phish,recall_phish,fpr_benign,miss_phish,roc_auc,average_precision,mcc
0,phreshphish_temporal_test,lightgbm,13,2.217912,0.5,168035,1234,90025,5449,71327,0.599064,0.442058,0.929027,0.986478,0.070973,0.382566,0.400534,-0.146445
1,phiusiil_random_test_reference,lightgbm,13,2.217912,0.5,47074,26942,28,133,19971,0.995985,0.998600,0.993384,0.001038,0.006616,0.998101,0.998554,0.993017
2,phreshphish_temporal_test,lightgbm,42,2.030285,0.5,168035,1234,90025,5449,71327,0.599064,0.442058,0.929027,0.986478,0.070973,0.382566,0.400534,-0.146445
3,phiusiil_random_test_reference,lightgbm,42,2.030285,0.5,47074,26942,28,133,19971,0.995985,0.998600,0.993384,0.001038,0.006616,0.998101,0.998554,0.993017
4,phreshphish_temporal_test,lightgbm,2024,2.203507,0.5,168035,1234,90025,5449,71327,0.599064,0.442058,0.929027,0.986478,0.070973,0.382566,0.400534,-0.146445
5,phiusiil_random_test_reference,lightgbm,2024,2.203507,0.5,47074,26942,28,133,19971,0.995985,0.998600,0.993384,0.001038,0.006616,0.998101,0.998554,0.993017
6,phreshphish_temporal_test,lightgbm,777,2.096036,0.5,168035,1234,90025,5449,71327,0.599064,0.442058,0.929027,0.986478,0.070973,0.382566,0.400534,-0.146445
7,phiusiil_random_test_reference,lightgbm,777,2.096036,0.5,47074,26942,28,133,19971,0.995985,0.998600,0.993384,0.001038,0.006616,0.998101,0.998554,0.993017
8,phreshphish_temporal_test,lightgbm,31415,2.048362,0.5,168035,1234,90025,5449,71327,0.599064,0.442058,0.929027,0.986478,0.070973,0.382566,0.400534,-0.146445
9,phiusiil_random_test_reference,lightgbm,31415,2.048362,0.5,47074,26942,28,133,19971,0.995985,0.998600,0.993384,0.001038,0.006616,0.998101,0.998554,0.993017
10,phreshphish_temporal_test,xgboost,13,2.351836,0.5,168035,2265,88994,5552,71224,0.601062,0.444544,0.927686,0.975181,0.072314,0.324871,0.354125,-0.112337
11,phiusiil_random_test_reference,xgboost,13,2.351836,0.5,47074,26945,25,149,19955,0.995659,0.998749,0.992589,0.000927,0.007411,0.998172,0.998591,0.992455
12,phreshphish_temporal_test,xgboost,42,1.816835,0.5,168035,2265,88994,5552,71224,0.601062,0.444544,0.927686,0.975181,0.072314,0.324871,0.354125,-0.112337
13,phiusiil_random_test_reference,xgboost,42,1.816835,0.5,47074,26945,25,149,19955,0.995659,0.998749,0.992589,0.000927,0.007411,0.998172,0.998591,0.992455
14,phreshphish_temporal_test,xgboost,2024,1.904719,0.5,168035,2265,88994,5552,71224,0.601062,0.444544,0.927686,0.975181,0.072314,0.324871,0.354125,-0.112337
15,phiusiil_random_test_reference,xgboost,2024,1.904719,0.5,47074,26945,25,149,19955,0.995659,0.998749,0.992589,0.000927,0.007411,0.998172,0.998591,0.992455
16,phreshphish_temporal_test,xgboost,777,1.786592,0.5,168035,2265,88994,5552,71224,0.601062,0.444544,0.927686,0.975181,0.072314,0.324871,0.354125,-0.112337
17,phiusiil_random_test_reference,xgboost,777,1.786592,0.5,47074,26945,25,149,19955,0.995659,0.998749,0.992589,0.000927,0.007411,0.998172,0.998591,0.992455
18,phreshphish_temporal_test,xgboost,31415,2.186228,0.5,168035,2265,88994,5552,71224,0.601062,0.444544,0.927686,0.975181,0.072314,0.324871,0.354125,-0.112337
19,phiusiil_random_test_reference,xgboost,31415,2.186228,0.5,47074,26945,25,149,19955,0.995659,0.998749,0.992589,0.000927,0.007411,0.998172,0.998591,0.992455

## Primary-seed registrable-domain bootstrap
For each model's primary seed (42), sample target registrable domains with replacement 1,000 times (RNG seed 42). Report percentile 95% intervals. This is uncertainty conditional on the one fitted model and one target period, not future-period generalization.

In [4]:
rng=np.random.default_rng(BOOT_SEED)
intervals=[]
for model_name in ("lightgbm","xgboost"):
    frame=pd.read_csv(OUT/f"predictions_phreshphish_temporal_test_{model_name}_seed{PRIMARY_SEED}.csv.gz")
    grouped=frame.groupby("domain",sort=True).indices
    domains=np.array(list(grouped),dtype=object)
    values={k:[] for k in ("f1_phish","precision_phish","recall_phish","fpr_benign","miss_phish","roc_auc","average_precision","mcc")}
    for _ in range(BOOT_REPS):
        chosen=rng.choice(domains,size=len(domains),replace=True)
        ix=np.concatenate([grouped[d] for d in chosen])
        y=frame.y_phish.to_numpy()[ix]; p=frame.p_phish.to_numpy()[ix]
        if len(np.unique(y))<2: continue
        s=score(y,p)
        for key in values: values[key].append(s[key])
    estimate=score(frame.y_phish.to_numpy(),frame.p_phish.to_numpy())
    for key,samples in values.items():
        intervals.append({"cohort":"phreshphish_temporal_test","model":model_name,"seed":PRIMARY_SEED,"metric":key,"estimate":estimate[key],"lower95":np.quantile(samples,.025),"upper95":np.quantile(samples,.975),"valid_replicates":len(samples),"domains":len(domains),"replicates":BOOT_REPS,"bootstrap_seed":BOOT_SEED})
ci=pd.DataFrame(intervals)
ci.to_csv(OUT/"primary_seed_domain_bootstrap.csv",index=False)
assert (ci.valid_replicates==BOOT_REPS).all()
display(ci)

,cohort,model,seed,metric,estimate,lower95,upper95,valid_replicates,domains,replicates,bootstrap_seed
0,phreshphish_temporal_test,lightgbm,42,f1_phish,0.599064,0.538701,0.669829,1000,65288,1000,42
1,phreshphish_temporal_test,lightgbm,42,precision_phish,0.442058,0.381220,0.519504,1000,65288,1000,42
2,phreshphish_temporal_test,lightgbm,42,recall_phish,0.929027,0.914475,0.944563,1000,65288,1000,42
3,phreshphish_temporal_test,lightgbm,42,fpr_benign,0.986478,0.984874,0.988138,1000,65288,1000,42
4,phreshphish_temporal_test,lightgbm,42,miss_phish,0.070973,0.055437,0.085525,1000,65288,1000,42
5,phreshphish_temporal_test,lightgbm,42,roc_auc,0.382566,0.353178,0.413481,1000,65288,1000,42
6,phreshphish_temporal_test,lightgbm,42,average_precision,0.400534,0.357787,0.459478,1000,65288,1000,42
7,phreshphish_temporal_test,lightgbm,42,mcc,-0.146445,-0.175573,-0.111340,1000,65288,1000,42
8,phreshphish_temporal_test,xgboost,42,f1_phish,0.601062,0.541201,0.669748,1000,65288,1000,42
9,phreshphish_temporal_test,xgboost,42,precision_phish,0.444544,0.383774,0.520178,1000,65288,1000,42
10,phreshphish_temporal_test,xgboost,42,recall_phish,0.927686,0.913042,0.943893,1000,65288,1000,42
11,phreshphish_temporal_test,xgboost,42,fpr_benign,0.975181,0.972491,0.977816,1000,65288,1000,42
12,phreshphish_temporal_test,xgboost,42,miss_phish,0.072314,0.056107,0.086958,1000,65288,1000,42
13,phreshphish_temporal_test,xgboost,42,roc_auc,0.324871,0.302259,0.345730,1000,65288,1000,42
14,phreshphish_temporal_test,xgboost,42,average_precision,0.354125,0.299011,0.432051,1000,65288,1000,42
15,phreshphish_temporal_test,xgboost,42,mcc,-0.112337,-0.141845,-0.078580,1000,65288,1000,42

## Recompute and provenance manifest
Independently recompute every metric from serialized prediction files (not the in-memory results), then persist the comparison. Hash source inputs and generated results; record package versions and execution environment.

In [5]:
# Independent recomputation is from CSV reloads; compare all metrics and counts.
check_rows=[]
for _,row in metrics_df.iterrows():
    path=OUT/f"predictions_{row.cohort}_{row.model}_seed{int(row.seed)}.csv.gz"
    saved=pd.read_csv(path)
    got=score(saved.y_phish.to_numpy(),saved.p_phish.to_numpy())
    for key,value in got.items():
        expected=row[key]
        assert np.isclose(value,expected,rtol=0,atol=1e-12,equal_nan=True),(path.name,key,value,expected)
        check_rows.append({"file":path.name,"metric":key,"saved_prediction_recompute":value,"metrics_csv":expected,"absolute_difference":abs(value-expected) if np.isfinite(value) else 0.0,"pass":True})
check_path=OUT/"independent_metrics_check.csv"
pd.DataFrame(check_rows).to_csv(check_path,index=False)
input_paths=[phi_path,split_path,target_path,*sorted(PHRESH_DIR.glob("test-*.parquet")),EXP5/"src/features.py",EXP5/"src/data.py",EXP5/"src/run_experiment.py",HERE/"create_notebook.py"]
manifest={"protocol":"A2 zero-shot PhiUSIIL train → cleaned PhreshPhish temporal test","threshold":THRESHOLD,"positive_label":"phishing=1; benign=0","seeds":SEEDS,"primary_seed":PRIMARY_SEED,"feature_order":FEATURE_ORDER,"model_params":MODEL_PARAMS,"threads":4,"bootstrap":{"unit":"registrable domain","replicates":BOOT_REPS,"rng_seed":BOOT_SEED},"input_hashes":{str(p.relative_to(ROOT)):sha256(p) for p in input_paths},"output_hashes":{p.name:sha256(p) for p in [metrics_path,OUT/"primary_seed_domain_bootstrap.csv",check_path,*prediction_files]},"environment":{"python":platform.python_version(),"packages":{name:md.version(name) for name in ["numpy","pandas","scikit-learn","lightgbm","xgboost","pyarrow","tldextract","nbformat","nbclient"]}},"rows":{"phiusiil_train":len(Xtr),"phiusiil_reference_test":len(Xref),"phreshphish_temporal_test":len(Xt)},"independent_prediction_metric_checks":len(check_rows)}
(OUT/"manifest.json").write_text(json.dumps(manifest,indent=2),encoding="utf-8")
print(json.dumps(manifest,indent=2))

{
  "protocol": "A2 zero-shot PhiUSIIL train \u2192 cleaned PhreshPhish temporal test",
  "threshold": 0.5,
  "positive_label": "phishing=1; benign=0",
  "seeds": [
    13,
    42,
    2024,
    777,
    31415
  ],
  "primary_seed": 42,
  "feature_order": [
    "URLLength",
    "DomainLength",
    "TLDLength",
    "NoOfSubDomain",
    "NoOfObfuscatedChar",
    "ObfuscationRatio",
    "NoOfLettersInURL",
    "LetterRatioInURL",
    "NoOfDegitsInURL",
    "DegitRatioInURL",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL",
    "SpacialCharRatioInURL",
    "IsHTTPS",
    "HasObfuscation",
    "IsDomainIP"
  ],
  "model_params": {
    "lightgbm": {
      "n_estimators": 300,
      "learning_rate": 0.05,
      "num_leaves": 63,
      "verbose": -1
    },
    "xgboost": {
      "n_estimators": 300,
      "learning_rate": 0.05,
      "max_depth": 8,
      "eval_metric": "logloss",
      "tree_method": "hist"
    }
  },
  "threads": 4,
  "bootstrap": {
    "unit": "registrable domain",
    "replicates": 1000,
    "rng_seed": 42
  },
  "input_hashes": {
    "Experiment\\1 - PhiUSIIL Cleaning + Leakage-Audit Notebook\\phiusill_clean\\phiusiil_clean.parquet": "4c86b580ddc694c1a6bd2b0f249b43550508b2935be85c09b34dbaf67273468f",
    "Experiment\\1 - PhiUSIIL Cleaning + Leakage-Audit Notebook\\phiusill_clean\\split_random.csv": "9520d9bd891c2fe443732a64d0484d52f32c434afa1cc61bd1c21f669a117ab3",
    "Experiment\\4 - PhreshPhish Temporal Audit\\outputs\\20261022T170935017991Z\\split_test.csv.gz": "b05907450beb66d5e697055b16a9204036b437344e483c417e8bbc0fb01abd04",
    "dataset\\PhreshPhish\\data\\test-000.parquet": "9ae7908b64cc75669e4be4cbd0fec884ac2b3f4984211eacfbf013a2ada12851",
    "dataset\\PhreshPhish\\data\\test-001.parquet": "bb122ccb309436b92e7edf11792d53efdbde46c4b5d2ad7d39a7d48b50d2b00f",
    "dataset\\PhreshPhish\\data\\test-002.parquet": "da3e9b1fb7e537ea951bb6e9ac68ae5a0c48e6590714f2b90ecf5dd96276d894",
    "dataset\\PhreshPhish\\data\\test-003.parquet": "c6157aeddfc5eff2728e88ccc61186464e4e6861bee0ae841a830be9ebc7cf17",
    "dataset\\PhreshPhish\\data\\test-004.parquet": "b20de434400f3030dd711a1e4f6e012397d1c2889d575b21aa747f8c5ae04df1",
    "dataset\\PhreshPhish\\data\\test-005.parquet": "19b0ecd6a657a11a3fb43dcb22e260eb5b5c8d7a0dcee880b4705a9ee2ef1c6f",
    "dataset\\PhreshPhish\\data\\test-006.parquet": "a34c4ad85cf863af950cad8251717cba3642ae0c0e7bd8ab245a29a63139d187",
    "dataset\\PhreshPhish\\data\\test-007.parquet": "f91281ac9a8bbf39fe9146e115be5e74cf3d59719c2f06bb38178fbaa9d6719b",
    "dataset\\PhreshPhish\\data\\test-008.parquet": "82e7216cef17bd78f83ee3339a980d0e09ef864c83f3e8222ef809b961821252",
    "dataset\\PhreshPhish\\data\\test-009.parquet": "a18e27d35f3a06983c1734f875093f45dbd041ea39e796f8d762f5712f800be6",
    "dataset\\PhreshPhish\\data\\test-010.parquet": "b5d9ca33207b70e2c22aeef6cdec1f294a7ce5f843c6033e208c6f520c85cfdd",
    "dataset\\PhreshPhish\\data\\test-011.parquet": "585cf9cfa0ddb54421bfccedb26590dd87426908e814f1290b1986c2e750f0e5",
    "dataset\\PhreshPhish\\data\\test-012.parquet": "3bbffccd4269ac723febeacc01905b2d52d1f98242f5bf18a82093cc4f4cdf97",
    "dataset\\PhreshPhish\\data\\test-013.parquet": "81daa4b68fca7b2df4d144145e80a09355d963e290d277c9976fb5a988b5e1f3",
    "dataset\\PhreshPhish\\data\\test-014.parquet": "8e30a3b2419604ce578f341392bd6e3878abdae38d7b3e38adb107bf2f557c03",
    "dataset\\PhreshPhish\\data\\test-015.parquet": "9d2589e528116c862aba4eed4ce0b4778172e8b82f2ac3c4157153666bb68adc",
    "dataset\\PhreshPhish\\data\\test-016.parquet": "3d9f97863ee0c88448487d4a13c4947951d62e65e571ed695e8bb69108995ba7",
    "dataset\\PhreshPhish\\data\\test-017.parquet": "66b916bc81a28f172ee807acedb497096993f64266459af8d785bc09d4d127d1",
    "dataset\\PhreshPhish\\data\\test-018.parquet": "aaa23d30b1c242b94000b5243dfb855f715f95fdbc0fd345f9ec4d30aeda36b1",
    "dataset\\PhreshPhish\\data\\test-019.parquet": "c7169aa4564a95e4950f05bc3281a66fe58f2b31eb1594b62a693de65da7508c",
    "dataset\\PhreshPhish\\data\\test-020.parquet": "77d312fe7dc92fc3b2ed208ab55b148b2032345091ad44d513b479241013d18e",
    "Experiment\\5 - PhiUSIIL Focused Ablation\\src\\features.py": "81822b4fac8b50cdf93371651e3c94680628ef189d64c32429ec15cc51cd48e6",
    "Experiment\\5 - PhiUSIIL Focused Ablation\\src\\data.py": "3212e581b47f5626125203c6bcbf9c622b89ae9485740f5346bb505975db1108",
    "Experiment\\5 - PhiUSIIL Focused Ablation\\src\\run_experiment.py": "9aebb54cf92b78efb82a00db454732bd6578c0cce3b26c07a94d08d7f1410d3c",
    "Experiment\\6 - Cross-Corpus Transfer\\create_notebook.py": "29f3f6782886764c482a27e74a40ff325d68fd36311eb22ecf5f4a57525d00e1"
  },
  "output_hashes": {
    "metrics.csv": "e0f2e6861f99f8204b2285d8d1c2a47a1a33b7eccb6f82f8a27520ba7e0a67d4",
    "primary_seed_domain_bootstrap.csv": "03ef7e76dfadc36cdae113dd1455c201b7bcdb07dd2791fb2dc0c47582937cda",
    "independent_metrics_check.csv": "368639c03d1cb25dd99d4d4666d6568e0707e0c64ec138139284acb896b67e3d",
    "predictions_phreshphish_temporal_test_lightgbm_seed13.csv.gz": "657044572d7e473823b5add2fb53f0bda0fac3ceaabdda36868fdcfa18b34b9b",
    "predictions_phiusiil_random_test_reference_lightgbm_seed13.csv.gz": "cffe927bcd0899b7c785f23aa337fadb866cfa576788c689c382b12252d6ce11",
    "predictions_phreshphish_temporal_test_lightgbm_seed42.csv.gz": "84c329719faa895e79ef1d61956434238eab7fc605b380585ce8a17b9ec4e785",
    "predictions_phiusiil_random_test_reference_lightgbm_seed42.csv.gz": "7e10164557399753a7c33b40f0f420d36e3a51da04db9895bd9b44db51ea440d",
    "predictions_phreshphish_temporal_test_lightgbm_seed2024.csv.gz": "b498cac11f5c09cea6f657855007845f40e93a0fd7282d00445bbd89fc79f123",
    "predictions_phiusiil_random_test_reference_lightgbm_seed2024.csv.gz": "b2618bf15c923f9c9d6a8bb13a3d016581a7f06588d14d9e98867eed5194243c",
    "predictions_phreshphish_temporal_test_lightgbm_seed777.csv.gz": "88a3994580afcbb1e6cd15ce91306ced7f4171d880b41c26754579bd1a0c615e",
    "predictions_phiusiil_random_test_reference_lightgbm_seed777.csv.gz": "4a2567485b9cd9147c13c347b851d950752ab884a29ae7a3fc5eced8a55b9b19",
    "predictions_phreshphish_temporal_test_lightgbm_seed31415.csv.gz": "8c985781e728f0c585b3670517335f927c0317be3919f3d3796f441277112250",
    "predictions_phiusiil_random_test_reference_lightgbm_seed31415.csv.gz": "5b94532399ef9c473015ec4e487c225e30b1946dcf6c3b49ab8c85b4dbfc8e19",
    "predictions_phreshphish_temporal_test_xgboost_seed13.csv.gz": "e5afff48926f9afe9d5535c116f38fba81231b0826f587344d4a2500b51e7e72",
    "predictions_phiusiil_random_test_reference_xgboost_seed13.csv.gz": "a58182c58f7a298424ef872bf58ca12dbd868492c0f9e990ad5c096360382495",
    "predictions_phreshphish_temporal_test_xgboost_seed42.csv.gz": "2760cb277f1017670f5eb0754bd1724da7a79f294feae8717f7ba015a7c34484",
    "predictions_phiusiil_random_test_reference_xgboost_seed42.csv.gz": "777942b2f512437eaccddc4a4ff442d1e0dc51afbeede97e688f71b259ab628f",
    "predictions_phreshphish_temporal_test_xgboost_seed2024.csv.gz": "5a091f371bd910119a1f6337ae174b9eb59d8832b301b8a7efcf2fb28aef780a",
    "predictions_phiusiil_random_test_reference_xgboost_seed2024.csv.gz": "b79006f48b62baf719fb00d79cf2dfd3ea36204f45f691466316483fc28289c1",
    "predictions_phreshphish_temporal_test_xgboost_seed777.csv.gz": "840790d10c0e1a784faee3d98697a0c453881f1fe5da7aa58d7dec3214055f98",
    "predictions_phiusiil_random_test_reference_xgboost_seed777.csv.gz": "0c1c2b00a847933f079217c88632722c819a889782ae0d0bcc7d39f6de431646",
    "predictions_phreshphish_temporal_test_xgboost_seed31415.csv.gz": "7283b8d79d730b66861c3826674798f60948477c3a498f1852bdd9a6f2b37772",
    "predictions_phiusiil_random_test_reference_xgboost_seed31415.csv.gz": "7785030161c1b15743cc11628afff90623bc569fd795d159a8fc08f33ad0b907"
  },
  "environment": {
    "python": "3.14.7",
    "packages": {
      "numpy": "2.5.3",
      "pandas": "3.1.0",
      "scikit-learn": "1.9.1",
      "lightgbm": "4.7.0",
      "xgboost": "3.4.1",
      "pyarrow": "26.0.0",
      "tldextract": "5.4.0",
      "nbformat": "5.11.1",
      "nbclient": "0.11.0"
    }
  },
  "rows": {
    "phiusiil_train": 141222,
    "phiusiil_reference_test": 47074,
    "phreshphish_temporal_test": 168035
  },
  "independent_prediction_metric_checks": 260
}

## Limitations
- No PhreshPhish target data used during fitting or threshold selection.
- PhiUSIIL reference is in-domain and non-paired; cross-dataset difference is not a controlled causal contrast.
- Earlier target inspection makes this exploratory, not blind prospective testing.
- Five seeds measure training stochasticity, not independent target periods.
- Target period reflects time and population shift together.
- Registrable domains can combine unrelated tenants; bootstrap does not establish independent organizations. Private PSL suffixes disabled by the shared extractor.
- Dataset collection and label provenance may differ. Results apply only to the documented cleaned target cohort.